### ISSUE TITLE
Bugfix: Fixing the labels

### ISSUE THREAD

**Issue by agnmmd** [kuleshov/cornell-cs5785-2022-applied-ml#11]
This suggest a fix to the labels used in the plot linked below:

https://github.com/kuleshov/cornell-cs5785-2022-applied-ml/blob/fab3401185850553f5289a4b78e48c70b2d2fc4d/lecture-notes/lecture2-supervised-learning.ipynb#L2157C6-L2157C78

fix: `plt.legend(['Initial patients', 'New patients', 'Prediction'])`

ps: The same applies to the 2020 edition of the course.

**Comment by kuleshov** [comment]
thank you for your note! happy to merge a PR
